"""Tokens and Tokenizer for marple.

Each lexical category is its own dataclass subclass of `Token`.
Singletons (delimiters, parens, etc.) carry no payload; payload-
bearing tokens (`IdToken`, `NumberToken`, `OperatorToken`, …)
declare their typed field directly. The parser dispatches via
`isinstance(tok, FooToken)`, eliminating the previous
`tok.type == TokenType.FOO` + `assert isinstance(tok.value, ...)`
two-step.
"""

from dataclasses import dataclass


def _isdigit(ch: str) -> bool:
    return "0" <= ch <= "9"

def _isalpha(ch: str) -> bool:
    return ("a" <= ch <= "z") or ("A" <= ch <= "Z") or ch in "∆⍙"

def _isalnum(ch: str) -> bool:
    return _isdigit(ch) or _isalpha(ch)


@dataclass
class Token:
    """Base class. Equality auto-generated by @dataclass per
    subclass: same-class comparisons compare fields, cross-class
    comparisons return NotImplemented (i.e. unequal)."""


# ── Payload-bearing tokens ──

@dataclass
class NumberToken(Token):
    value: int | float

@dataclass
class StringToken(Token):
    value: str

@dataclass
class IdToken(Token):
    name: str

@dataclass
class FunctionToken(Token):
    glyph: str

@dataclass
class OperatorToken(Token):
    glyph: str

@dataclass
class SysVarToken(Token):
    name: str

@dataclass
class QualifiedNameToken(Token):
    name: str


# ── Singleton tokens (no payload) ──

@dataclass
class LParenToken(Token): pass
@dataclass
class RParenToken(Token): pass
@dataclass
class AssignToken(Token): pass
@dataclass
class DiamondToken(Token): pass
@dataclass
class LBraceToken(Token): pass
@dataclass
class RBraceToken(Token): pass
@dataclass
class OmegaToken(Token): pass
@dataclass
class AlphaToken(Token): pass
@dataclass
class AlphaAlphaToken(Token): pass
@dataclass
class OmegaOmegaToken(Token): pass
@dataclass
class NablaToken(Token): pass
@dataclass
class GuardToken(Token): pass
@dataclass
class LBracketToken(Token): pass
@dataclass
class RBracketToken(Token): pass
@dataclass
class SemicolonToken(Token): pass
@dataclass
class ZildeToken(Token): pass
@dataclass
class EofToken(Token): pass


FUNCTION_GLYPHS = set("!+-×÷⌈⌊*⍟|<≤=≥>≠∧∨~⍴⍳,↑↓⌽⊖⍉⍋⍒⊤⊥⍎⍕⌹○⌷≡≢∈?")

SINGLE_CHAR_TOKENS: dict[str, Token] = {
    "(": LParenToken(),
    ")": RParenToken(),
    "←": AssignToken(),
    "⋄": DiamondToken(),
    "/": OperatorToken("/"),
    "⌿": OperatorToken("⌿"),
    "\\": OperatorToken("\\"),
    "⍀": OperatorToken("⍀"),
    ".": OperatorToken("."),
    "∘": OperatorToken("∘"),
    "⍤": OperatorToken("⍤"),
    "⍣": OperatorToken("⍣"),
    "⌶": OperatorToken("⌶"),
    "⍨": OperatorToken("⍨"),
    "{": LBraceToken(),
    "}": RBraceToken(),
    "⍵": OmegaToken(),
    "⍺": AlphaToken(),
    "∇": NablaToken(),
    ":": GuardToken(),
    "[": LBracketToken(),
    "]": RBracketToken(),
    ";": SemicolonToken(),
    "⍬": ZildeToken(),
}


class Tokenizer:
    def __init__(self, source: str) -> None:
        self._source = source
        self._pos = 0

    def _current(self) -> str | None:
        if self._pos >= len(self._source):
            return None
        return self._source[self._pos]

    def _advance(self) -> None:
        self._pos += 1

    def _skip_whitespace(self) -> None:
        while self._current() is not None and self._current() in (" ", "\t", "\r", "\n"):
            self._advance()

    def _read_number(self) -> NumberToken:
        result = ""
        has_dot = False
        while self._current() is not None and (_isdigit(self._current()) or self._current() == "."):  # type: ignore[union-attr]
            if self._current() == ".":
                if has_dot:
                    break
                has_dot = True
            result += self._current()  # type: ignore[operator]
            self._advance()
        # Handle scientific notation: 1E¯14, 1E3, 1e-14, 1.5E3
        if self._current() is not None and self._current() in ("e", "E"):
            result += self._current()  # type: ignore[operator]
            self._advance()
            if self._current() is not None and self._current() == "¯":
                result += "-"  # APL high minus → Python minus for float()
                self._advance()
            elif self._current() is not None and self._current() in ("-", "+"):
                result += self._current()  # type: ignore[operator]
                self._advance()
            while self._current() is not None and _isdigit(self._current()):  # type: ignore[union-attr]
                result += self._current()  # type: ignore[operator]
                self._advance()
            return NumberToken(float(result))
        value: int | float = float(result) if has_dot else int(result)
        return NumberToken(value)

    def _read_string(self) -> StringToken:
        self._advance()  # skip opening quote
        result = ""
        while self._current() is not None and self._current() != "'":
            result += self._current()  # type: ignore[operator]
            self._advance()
        if self._current() == "'":
            self._advance()  # skip closing quote
        return StringToken(result)

    def _read_id(self) -> IdToken | QualifiedNameToken:
        result = ""
        while self._current() is not None and (_isalnum(self._current()) or self._current() == "_"):  # type: ignore[union-attr]
            result += self._current()  # type: ignore[operator]
            self._advance()
        # Check for :: (qualified name)
        if (
            self._current() == ":"
            and self._pos + 1 < len(self._source)
            and self._source[self._pos + 1] == ":"
            and self._pos + 2 < len(self._source)
            and (_isalpha(self._source[self._pos + 2]) or self._source[self._pos + 2] == "_")
        ):
            result += "::"
            self._advance()  # skip first :
            self._advance()  # skip second :
            rest = self._read_id()
            rest_name = rest.name
            return QualifiedNameToken(result + rest_name)
        return IdToken(result)

    def tokenize(self) -> list[Token]:
        tokens: list[Token] = []
        while self._current() is not None:
            self._skip_whitespace()
            ch = self._current()
            if ch is None:
                break
            if ch == "⍝":
                break
            if ch == "'":
                tokens.append(self._read_string())
            elif ch == "⍞":
                tokens.append(SysVarToken("⍞"))
                self._advance()
            elif ch == "⎕":
                self._advance()
                name = ""
                while self._current() is not None and _isalpha(self._current()):  # type: ignore[union-attr]
                    name += self._current()  # type: ignore[operator]
                    self._advance()
                tokens.append(SysVarToken("⎕" + name.upper()))
            elif ch == "¯":
                self._advance()
                num_token = self._read_number()
                tokens.append(NumberToken(-num_token.value))
            elif _isdigit(ch):
                tokens.append(self._read_number())
            elif ch in FUNCTION_GLYPHS:
                tokens.append(FunctionToken(ch))
                self._advance()
            elif ch == "⍺" and self._pos + 1 < len(self._source) and self._source[self._pos + 1] == "⍺":
                tokens.append(AlphaAlphaToken())
                self._advance()
                self._advance()
            elif ch == "⍵" and self._pos + 1 < len(self._source) and self._source[self._pos + 1] == "⍵":
                tokens.append(OmegaOmegaToken())
                self._advance()
                self._advance()
            elif ch in SINGLE_CHAR_TOKENS:
                tokens.append(SINGLE_CHAR_TOKENS[ch])
                self._advance()
            elif ch == "$" and self._pos + 2 < len(self._source) and self._source[self._pos + 1] == ":" and self._source[self._pos + 2] == ":":
                self._advance()  # skip $
                self._advance()  # skip first :
                self._advance()  # skip second :
                rest = self._read_id()
                rest_name = rest.name
                tokens.append(QualifiedNameToken("$::" + rest_name))
            elif _isalpha(ch) or ch == "_":
                tokens.append(self._read_id())
            else:
                # Defensive: any character that reached this point is
                # unrecognised. The previous behaviour (`self._advance()`)
                # silently dropped the char, which masked two real bugs
                # discovered on 2026-04-09 — the missing zilde literal
                # (⍬) and the missing commute operator (⍨), both of
                # which were silently swallowed and produced confusing
                # downstream errors. Raising here surfaces the same
                # class of bug immediately and clearly.
                from marple.errors import SyntaxError_
                raise SyntaxError_(f"Unknown character: {ch!r}")
        tokens.append(EofToken())
        return tokens
